### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by luisgrases** [arjusmoon860/strapi-google-auth#6]
After enabling the plugin on plugins.ts I get compilation errors when running strapi on development:
```
export default ({ env }) => ({
  "google-auth": {
    enabled: true
  },
});
```

Error message: 

```
Building your admin UI with development configuration...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.resolve (node:path:1098:7)
    at /Users/luisgrases/projects/seano/node_modules/@strapi/admin/utils/create-cache-dir.js:82:33
    at Array.filter (<anonymous>)
    at createCacheDir (/Users/luisgrases/projects/seano/node_modules/@strapi/admin/utils/create-cache-dir.js:80:6)
    at async Object.build (/Users/luisgrases/projects/seano/node_modules/@strapi/admin/index.js:27:3)
    at async primaryProcess (/Users/luisgrases/projects/seano/node_modules/@strapi/strapi/lib/commands/develop.js:62:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by luisgrases** [comment]
Fixed it. I had to change the plugins.ts like so:

```
export default ({ env }) => ({
  "strapi-google-auth": {
    enabled: true
  },
});
```

**Comment by kevinblanco** [comment]
This should be updated for sure, was getting the same error and your comment fixed it.

**Comment by fskarmeta** [comment]
Hi, thanks for pointing this out.

**Comment by arjusmoon860** [comment]
The docs has been updated.
